import {
	Award,
	Brush,
	FlaskConical,
	Layers,
	BookOpen,
	Calendar,
	CheckCircle2,
	Clock,
	Coffee,
	Compass,
	Flame,
	Gift,
	Globe,
	Hammer,
	Heart,
	Instagram,
	Leaf,
	Lightbulb,
	Mail,
	MapPin,
	MessageCircle,
	Package,
	Palette,
	Phone,
	Rocket,
	ShieldCheck,
	ShoppingBag,
	Sparkles,
	Star,
	Sun,
	Users,
	Wrench,
	Zap,
	type LucideIcon,
} from "lucide-react";

export const blockIcons: Record<string, LucideIcon> = {
	award: Award,
	brush: Brush,
	"flask-conical": FlaskConical,
	layers: Layers,
	"book-open": BookOpen,
	calendar: Calendar,
	"check-circle": CheckCircle2,
	clock: Clock,
	coffee: Coffee,
	compass: Compass,
	flame: Flame,
	gift: Gift,
	globe: Globe,
	hammer: Hammer,
	heart: Heart,
	instagram: Instagram,
	leaf: Leaf,
	lightbulb: Lightbulb,
	mail: Mail,
	"map-pin": MapPin,
	"message-circle": MessageCircle,
	package: Package,
	palette: Palette,
	phone: Phone,
	rocket: Rocket,
	"shield-check": ShieldCheck,
	"shopping-bag": ShoppingBag,
	sparkles: Sparkles,
	star: Star,
	sun: Sun,
	users: Users,
	wrench: Wrench,
	zap: Zap,
};

export function resolveBlockIcon(name: string | undefined): LucideIcon | undefined {
	if (!name) return undefined;
	const kebab = name.trim().replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/[\s_]+/g, "-").toLowerCase();
	return blockIcons[kebab];
}
