from __future__ import annotations

BODY_TOP_MARGIN_MILLIMETERS = 16.0
BODY_SIDE_MARGIN_MILLIMETERS = 16.0
BODY_BOTTOM_MARGIN_MILLIMETERS = 20.0

GROW_SPACE_LIMIT = 1.5
GROW_TYPE_LIMIT = 0.35
GROW_INSET_MILLIMETERS = 14.0
TIGHTEN_SPACE_LIMIT = 0.45
TIGHTEN_TYPE_LIMIT = 0.04
LEADING_LIMIT = 0.1
SHORT_PAGE_FILL = 0.7
GROWN_PAGE_FILL = 0.78
SPARSE_LAST_PAGE_FILL = 0.3
LIFT_SHARE_OF_FREE_SPACE = 0.4
SEARCH_STEPS = 5

SPARSE_PAGE_FILL = 0.45
NEARLY_EMPTY_LAST_PAGE_FILL = 0.15
ORPHAN_LAST_PAGE_FILL = 0.3
ORPHAN_LAST_PAGE_LINES = 3
EARLY_PAGE_END_FILL = 0.7
LARGE_EMPTY_BAND_RATIO = 0.25
