from __future__ import annotations

from fonts.registry import BODY_SIZE_POINTS, SANS_BODY, default_family

COLOR_INK = (0x1C, 0x24, 0x30)
COLOR_MUTED = (0x6A, 0x72, 0x80)
COLOR_RULE = (0x37, 0x41, 0x51)
COLOR_BORDER = (0x9C, 0xA3, 0xAF)
COLOR_HEADER_FILL = (0xF3, 0xF4, 0xF6)

FONT_KOREAN_DOCX = default_family(SANS_BODY).name

SIZE_TITLE = 18.0
SIZE_CLAUSE_HEADING = 11.0
SIZE_BODY = BODY_SIZE_POINTS
SIZE_SMALL = 8.5
SIZE_LETTERHEAD_NAME = 11.5
SIZE_LETTERHEAD_DETAIL = 7.5
SIZE_FOOTER = 7.5

LINE_SPACING = 1.3
DOCX_PAGE_MARGIN_INCHES = 1.0
PDF_PAGE_MARGIN_MILLIMETERS = 16.0

TITLE_RULE_WIDTH_POINTS = 1.5
